#Pipeline for Azure Infrastructure Deployment
trigger:
  none

parameters:
  - name: prefix
    type: string
    default: 'prod'
  - name: location
    type: string
    default: 'East US'
  - name: resource_group_name
    type: string
    default: 'devops-infra-rg'

variables:
  - group: 'infra-spn'

pool:
  name: Default

steps:
- script: |
      az login --service-principal -u $(azureServicePrincipalId) -p $(azureServicePrincipalKey) --tenant $(azureTenantId)
      az account set --subscription $(azureSubscriptionId)
  displayName: 'Azure CLI Login'

- script: |
    cd infra
    terraform init -backend-config="key=${prefix}.terraform.tfstate"
    terraform apply -auto-approve -var="prefix=$(prefix)" -var="location=$(location)" -var="resource_group_name=$(resource_group_name)"