#Pipeline for Azure Infrastructure Deployment
trigger:
  none

variables:
  - group: 'infra-spn'

pool:
  name: Default

steps:
- task: TerraformCli@1
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
  env:
    ARM_CLIENT_ID: $(azureServicePrincipalId)
    ARM_CLIENT_SECRET: $(azureServicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(azureSubscriptionId)
    ARM_TENANT_ID: $(azureTenantId)
  displayName: 'Terraform Init'

- task: TerraformCli@1
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    commandOptions: >
      -auto-approve 

  env:
    ARM_CLIENT_ID: $(azureServicePrincipalId)
    ARM_CLIENT_SECRET: $(azureServicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(azureSubscriptionId)
    ARM_TENANT_ID: $(azureTenantId)
  displayName: 'Terraform Apply'