#Pipeline for Azure Infrastructure Deployment
trigger:
  none

parameters:
  - name: prefix
    type: string
    default: 'prod'
  - name: location
    type: string
    default: 'East US'
  - name: resource_group_name
    type: string
    default: 'devops-infra-rg'

variables:
  - group: 'infra-spn'

pool:
  name: Default

steps:
- task: TerraformCli@1
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
  env:
    ARM_CLIENT_ID: $(azureServicePrincipalId)
    ARM_CLIENT_SECRET: $(azureServicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(azureSubscriptionId)
    ARM_TENANT_ID: $(azureTenantId)
  displayName: 'Terraform Init'

- task: TerraformCli@1
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
    commandOptions: >
      -auto-approve 
      -var "prefix=$(prefix)" 
      -var "location=$(location)" 
      -var "resource_group_name=$(resource_group_name)"
  env:
    ARM_CLIENT_ID: $(azureServicePrincipalId)
    ARM_CLIENT_SECRET: $(azureServicePrincipalKey)
    ARM_SUBSCRIPTION_ID: $(azureSubscriptionId)
    ARM_TENANT_ID: $(azureTenantId)
  displayName: 'Terraform Apply'